agent:
  name: Cortex-R
  id: cortex_r_001
  description: >
    A reasoning-driven AI agent capable of using external tools
    and memory to solve complex tasks step-by-step.

strategy:
  type: conservative         # Options: conservative, retry_once, explore_all
  max_steps: 3               # Maximum tool-use iterations before termination

memory:
  top_k: 3
  type_filter: tool_output   # Options: tool_output, fact, query, all
  embedding_model: nomic-embed-text
  embedding_url: http://localhost:11434/api/embeddings

llm:
  text_generation: gemini
  embedding: nomic

persona:
  tone: concise
  verbosity: low
  behavior_tags: [rational, focused, tool-using]

mcp_servers:
  - id: math
    script: mcp_server_1.py
    cwd: C:/Users/dsaha/OneDrive - Microsoft/Documents/Personal/deep/study/artificial intelligence/eagv1/eag8/agent_e8/mcp_server
    type: stdio
  - id: documents
    script: mcp_server_2.py
    cwd: C:/Users/dsaha/OneDrive - Microsoft/Documents/Personal/deep/study/artificial intelligence/eagv1/eag8/agent_e8/mcp_server
    type: stdio
  - id: websearch
    script: mcp_server_3.py
    cwd: C:/Users/dsaha/OneDrive - Microsoft/Documents/Personal/deep/study/artificial intelligence/eagv1/eag8/agent_e8/mcp_server
    type: stdio
  - id: gmail
    url: http://localhost:8001
    type: sse
    description: "Gmail SSE Server"
    retry_attempts: 3
    timeout: 30
  - id: telegram
    type: sse
    url: http://localhost:8002
    description: "Telegram SSE Server"
    retry_attempts: 3
    timeout: 30

interaction_channel: CLI



# config/profiles.yaml → Agent Profiles / Persona Settings
# Role: Defines agent-specific config: name, strategy, preferences, tool categories.

# Responsibilities:

# Make agent identity configurable without touching code

# Store:

# Name, ID

# Strategy type

# Memory settings

# Tone/personality

# Dependencies:

# context.py and strategy.py load this on startup

# Format: YAML

# Example:

# yaml
# Copy
# Edit
# name: Cortex-R
# strategy: conservative
# memory:
#   top_k: 3
#   type_filter: tool_output
# tone: concise, helpful
# config/profiles.yaml
